<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'apimatic/jsonmapper' => array(
            'pretty_version' => 'v3.0.2',
            'version' => '3.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../apimatic/jsonmapper',
            'aliases' => array(),
            'reference' => '12e32cabc911d2af78f4d81f4ad5c06bd29391ca',
            'dev_requirement' => false,
        ),
        'apimatic/unirest-php' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../apimatic/unirest-php',
            'aliases' => array(),
            'reference' => 'a45c4c71a1ea3659b118042a67cc1b6486bcf03a',
            'dev_requirement' => false,
        ),
        'square/square' => array(
            'pretty_version' => '19.0.1.20220512',
            'version' => '19.0.1.20220512',
            'type' => 'library',
            'install_path' => __DIR__ . '/../square/square',
            'aliases' => array(),
            'reference' => '7852d8a09f818b1bdd929a6366afaa1dbc6bf5e9',
            'dev_requirement' => false,
        ),
    ),
);
