version: '3.9'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-rootsecret}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  db-data:
