@extends('client.layouts.app')
@section('meta')
<title>Terms & Conditions | JetOnset</title>
@endsection

@section('content')

<div class="section text-page"></div>

<div class="section page-text">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="mb-3">Privacy Policy JetOnset.</h2>
                <p class="mb-3">All information described in this Privacy Policy is processed by JetOnset, Inc. ("JetOnset", "we", "us", or "our") as a data controller. This Privacy Policy describes our practices related to the use, storage, and disclosure of personal information we collect from or about you when you interact with us in the course of our providing air charter transportation services, ancillary services, or other services provided by us, including when you use our website Jetonset.com ("Website") or our JetOnset App ("App"). This Privacy Policy also describes our processing of the personal data of individuals representing our business customers and suppliers.</p>
                <p class="mb-3"><strong>JetOnset reserves the right to modify this Privacy Policy at any time and without prior notice.</strong> We will post any changes to our Website. This Privacy Policy is not a contract and does not create any contractual rights or obligations.</p>
                
                <ol>
                    <li><strong>How to contact us.</strong> If you have any questions or comments regarding this Privacy Policy or any complaints about our adherence to it, please contact our Data Protection Officer, at Privacy@jetonset.com or contact our Customer Care Center by mail. We adhere to applicable notification requirements and reporting obligations to supervising authorities and/or data subjects regarding violations of this Privacy Policy as required by law. The substance and time frames applicable to these remedies are set forth in applicable laws.</li>
                    <li><strong>What information do we collect and when.</strong> Information related to a flight booking or purchase of our products or services, whether provided online, over the phone, emails or in person. Your name and title, date of birth, your national ID in certain circumstances, home address, phone number and email address, your billing and transaction information such as, credit/debit card type and number(s), corporate forms of payment and related data including associated billing address, expiration date(s) and security code(s).</li>
                    <li><strong>How do we use your information.</strong> To provide you with our services, assistance with booking, to confirm your travel arrangements and remind you about incomplete bookings. Take your payment and make any refunds or credits and send any confirmations. Manage and administer our services and business including performing our record-keeping requirements. Maintain the operational availability and reliability of our IT systems with infrastructure backups and testing. To confirm your identity and to prevent fraud. To improve our products and services. To send you marketing communications and offers. To share it with TSA for safety questions.</li>
                    <li><strong>Legal requirements.</strong> We may also use your personal information where this is necessary to comply with a reasonable request by a law enforcement or regulatory authority, body or agency, or in the defense of legal claims.</li>
                    <li><strong>Cookies.</strong> When you use our services, you may receive cookies or other similar technologies from us. We use them to determine that we give you a high quality experience on our services. We also use cookies to show you advertising that is relevant to you. There are four types of cookies used on our Services:
                        <ul class="dashed">
                            <li><i>Essential cookies.</i> They enable you to use our Services. These cookies are essential to enable you to browse our Services and use certain features. Without them some activities cannot be provided. These cookies also help keep our Services safe and secure.</li>
                            <li><i>Preference cookies.</i> These cookies store information such as your JetOnset login data and website preferences. Without these cookies, our Services may not be able to remember certain choices you've previously made or personalize your browsing experience by providing you with relevant information. These cookies can also be used to recognize your device so that you do not have to provide the same information more than once.</li>
                            <li><i>Performance cookies.</i> These cookies collect information about how you use our Services such as which pages you visit regularly. These cookies are used to provide you with a high-quality experience by doing things such as tracking page load, site response times, and error messages.</li>
                            <li><i>Content / Advertising cookies.</i> These cookies gather information about your use of our Services so we may improve your experience and provide you with more relevant content and advertising. They are also used to gather feedback on customer satisfaction through surveys. They remember that you've visited our Services and help us understand usage of our Services. Some of these cookies are from third parties that collect information about users of our Services (as described below under “Information collected by third parties on our Services”) in order to provide advertising (on our Services and elsewhere) based on users’ online activities (so-called "interest-based advertising") on our Services and elsewhere online. The third parties involved in interest-based advertising collect internet browsing information (e.g., websites visited, time of visit) across different websites and over time, and they may use the information they collect on our Services to provide you ads (from us and other companies) across the internet.</li>
                        </ul>
                    </li>
                    <li><strong>Information collected by third parties on our Services.</strong> Some of the content, advertising, and functionality on our Services may be provided by third parties, including third parties that are not affiliated with us. As noted above, these third parties may collect or receive technical information about your use of our Services, including through the use of cookies, pixel tags, web beacons, and other technologies, and this information may be collected over time and combined with information collected on different websites and online services. Some third parties collect information about users of our Services in order to provide interest-based advertising (on our Services and elsewhere, including across browsers and devices, also known as cross-device linking). This may include anonymized or de-identified information about you, such as travel destinations that you search for while using our Services. These third parties may use the information they collect on our Services to make predictions about your interests in order to provide you ads (from us and other companies) across the internet (for example, travel products and services that are available at a destination you searched for online). Some of these third parties may participate in an industry organization that gives users the opportunity to opt out of receiving ads that are tailored based on online activities. We may use Adobe Analytics or Google Analytics to aggregate and analyze data about your use of our Services.</li>
                    <li><strong>Minors.</strong> JetOnset does not knowingly collect personal information from children under the age of 13. If a child under 13 has provided us with personal information without parental or guardian consent, the parent or guardian may contact us by emailing us at privacy@jetonset.com. We will remove the information and unsubscribe the child from any of our electronic marketing lists.</li>
                    <li><strong>Information for California residents.</strong> Under the California Consumer Privacy Act of 2018 (“CCPA”): as a California resident you can request the following information about how we collected and used your personal information, - the categories of personal information that we collected, - the categories of sources from which we collected personal information, - the business or commercial purpose for collecting personal information, - the categories of third parties with whom we share personal information, - whether we have disclosed your personal information for a business purpose, and if so, the categories of personal information received by each category of third party recipient. You can request a copy of the personal information that we collected about you during the past 12 months. You can request that we delete the personal information that we collected from you. You are entitled to exercise the rights described above free from descrimination in the form of any unlawful denial of service, increase in the price of service, or suggestion that you may be penalized for exercising your rights. We do not sell your personal information to third parties, however, like many companies online, we use services provided by Google, Facebook, Adobe and others that help deliver interest-based ads to you as described in the section above entitled interest-based advertising. You can opt out of use of your personal information for interest-based advertising by emailing us at privacy@jetonset.com.</li>
                    
                    <li><strong>Information for European users.</strong> Except as otherwise specified, references to “personal information” in this Privacy Policy are equivalent to “personal data” governed by European data protection legislation. JetOnset Inc is the controller of your personal information covered by this Privacy Policy for purposes of the European data protection legislation. You may contact us at privacy@jetonset.com. European data protection laws give you certain rights regarding your personal information. If you are located in Europe you may ask us to take the following actions in relation to your personal information that we hold:
                        <ul class="dashed">
                            <li><strong>Access.</strong> Provide you with information about our processing of your personal information and give you access to your personal information.</li>
                            <li><strong>Correct.</strong> Update or correct inaccuracies in your personal information.</li>
                            <li><strong>Delete.</strong> Delete your personal information.</li>
                            <li><strong>Transfer.</strong> Transfer a machine‐readable copy of your personal information to you or a third party of your choice.</li>
                            
                            <li><strong>Restrict.</strong> Restrict the processing of your personal information.</li>
                            <li><strong>Object.</strong> Object to our reliance on our legitimate interests as the basis of our processing of your personal information that impacts your rights.</li>
                        </ul>
                        You may submit these requests by email to privacy@jetonset.com. We may request specific information from you to help us confirm your identity and process your request. Applicable law may require or permit us to decline your request. If we decline your request, we will tell you why, subject to legal restrictions. If you would like to submit a complaint about our use of your personal information or our response to your requests regarding your personal information, you may contact us at privacy@jetonset.com or submit a complaint to the data protection regulator in your jurisdiction.
                    </li>
                    <li><strong>Information security.</strong> Information Security is important to JetOnset. We have established appropriate physical, electronic, and managerial safeguards to protect the information we collect in accordance with our Privacy Policy. These safeguards are regularly reviewed to protect against unauthorized access, disclosure, and improper use of your information, and to maintain the accuracy and integrity of that data. In the event of a data breach, we adhere to data breach notification requirements and incident reporting obligations to supervising authorities and/or data subjects, as required by applicable laws. The substance and time frames applicable to these remedies are set forth in applicable laws.</li>
                </ol>
                
                
                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="font-weight-bold mb-0">Term one of the document</p>
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="font-weight-bold mb-0">Term two of the document</p>
                <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
</div>

@endsection